spring.application.name=SecurityEx

server.port=8090
#
#spring.security.user.name=vamsi
#spring.security.user.password=1234

spring.datasource.url=jdbc:postgresql://localhost:5432/vamsi
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
debug=true
